### ISSUE TITLE
Your website is flagged as insecure by Google

### ISSUE THREAD

**Issue by Max1Truc** [AmIJesse/Anonish-URL-shortener#2]
Google Safe Browsing flagged anoni.sh as a dangerous site : see [here](https://transparencyreport.google.com/safe-browsing/search?url=anoni.sh&hl=en) for the report.

It is annoying because it is now necessary to ask to ignore the fact that it's flagged as malicious on Firefox or Chrome to navigate to this site.

**Comment by AmIJesse** [comment]
Sorry for the late response, it should be fixed by now. It happened a couple time and I believe at this point google has flagged the site as a URL shortener, or something. I've gotten a few emails from them about malicious links to remove, but no more flags yet. At least not that I've seen.

**Comment by Max1Truc** [comment]
Ok ^^
